name: 'AzContainerOperations-Action'
description: 'Start, stop and restart containers from the Azure Container Instances'
author: 'klacol'
branding:
  icon: 'stop-circle'  
  color: 'green'
inputs:
  container-name:
    description: 'The name of the container, on which to commands shall be applied, eg. my-container'
    required: true
  command:
    description: 'The name of the command to run. One of start, stop or restart'
    required: true
  tenant: 
    description: 'Azure Service Principal Tenant ID'
    required: true
  username: 
    description: 'Azure Service Principal Username'
    required: true
  password:
    description: 'Azure Service Principal Token'
    required: true
  resource-group:
    description: 'The name of the resource group of the container, e.g. my.resource.group'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.container-name }}
    - ${{ inputs.command }}
    - ${{ inputs.tenant }}
    - ${{ inputs.resource-group }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
